"""AI feature F2: build the edge-AI benchmark models and export them for the ESP32.

Each model is built once in Keras with fixed random weights (this is a speed and
memory benchmark, not a trained model) and exported two ways:
  * plain C float32 arrays  -> ai/ai_bench_esp32/models_c.h
  * TFLite Micro int8        -> ai/ai_bench_esp32/models_tflm.h
Test inputs and reference outputs (Keras float, TFLite int8 on the PC) go to
bench_data.h so the ESP32 can check its own results.

Run:  ai/.venv/bin/python ai/bench/make_bench_models.py
"""
import os

os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")
import numpy as np  # noqa: E402
import tensorflow as tf  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "ai_bench_esp32")
SEED = 63
N_TEST = 4

tf.keras.utils.set_random_seed(SEED)
rng = np.random.default_rng(SEED)
L = tf.keras.layers


def models():
    """name -> (keras model, input shape, export to TFLM?)"""
    return {
        # Forecaster sized for 10 time steps x 3 features
        "mlp_s": (tf.keras.Sequential([L.Input((30,)), L.Dense(32, activation="relu"),
                                       L.Dense(32, activation="relu"), L.Dense(1)]), (30,), True),
        # Larger forecaster: 20 steps x 3 features
        "mlp_m": (tf.keras.Sequential([L.Input((60,)), L.Dense(64, activation="relu"),
                                       L.Dense(64, activation="relu"), L.Dense(1)]), (60,), True),
        # 1-D CNN over a 30-step window of 3 features
        "cnn": (tf.keras.Sequential([L.Input((30, 3)), L.Conv1D(16, 3, activation="relu"),
                                     L.Conv1D(16, 3, activation="relu"), L.GlobalAveragePooling1D(),
                                     L.Dense(1)]), (30, 3), True),
        # Recurrent forecaster (C only: GRU is not a TFLite Micro builtin)
        "gru": (tf.keras.Sequential([L.Input((30, 3)), L.GRU(32), L.Dense(1)]), (30, 3), False),
        # MPC plant model: [PM_in, CO_in, duty, PM_prev, RH, T, rpm, hour] -> next PM
        "plant": (tf.keras.Sequential([L.Input((8,)), L.Dense(16, activation="relu"), L.Dense(1)]), (8,), False),
    }


def carr(name, arr, ctype="float"):
    flat = np.asarray(arr).ravel()
    if ctype == "float":
        body = ", ".join(f"{v:.8e}f" for v in flat)
    else:
        body = ", ".join(str(int(v)) for v in flat)
    return f"static const {ctype} {name}[{flat.size}] = {{{body}}};\n"


def export_c(name, model):
    """Weights in the layouts c_infer.h expects."""
    out = []
    for i, layer in enumerate(model.layers):
        w = layer.get_weights()
        kind = type(layer).__name__
        if kind == "Dense":
            out.append(carr(f"{name}_d{i}_w", w[0].T))          # [out][in]
            out.append(carr(f"{name}_d{i}_b", w[1]))
        elif kind == "Conv1D":
            out.append(carr(f"{name}_c{i}_w", np.transpose(w[0], (2, 0, 1))))  # [cout][k][cin]
            out.append(carr(f"{name}_c{i}_b", w[1]))
        elif kind == "GRU":
            out.append(carr(f"{name}_g{i}_wk", w[0].T))         # [3u][in], gate order z, r, h
            out.append(carr(f"{name}_g{i}_uk", w[1].T))         # [3u][u]
            out.append(carr(f"{name}_g{i}_bi", w[2][0]))        # input bias
            out.append(carr(f"{name}_g{i}_br", w[2][1]))        # recurrent bias
    return "".join(out)


def to_tflite_int8(model, shape):
    def rep():
        for _ in range(200):
            yield [rng.normal(size=(1, *shape)).astype(np.float32)]
    conv = tf.lite.TFLiteConverter.from_keras_model(model)
    conv.optimizations = [tf.lite.Optimize.DEFAULT]
    conv.representative_dataset = rep
    conv.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    conv.inference_input_type = tf.int8
    conv.inference_output_type = tf.int8
    return conv.convert()


def tflite_ref(tfl, x):
    it = tf.lite.Interpreter(model_content=tfl)
    it.allocate_tensors()
    i, o = it.get_input_details()[0], it.get_output_details()[0]
    (si, zi), (so, zo) = i["quantization"], o["quantization"]
    outs = []
    for v in x:
        q = np.clip(np.round(v / si + zi), -128, 127).astype(np.int8)
        it.set_tensor(i["index"], q[None])
        it.invoke()
        outs.append((it.get_tensor(o["index"]).astype(np.float32).ravel()[0] - zo) * so)
    return np.array(outs, np.float32), (si, zi, so, zo)


def main():
    os.makedirs(OUT, exist_ok=True)
    hc = ["// Generated by ai/bench/make_bench_models.py - do not edit\n#pragma once\n"]
    ht = ["// Generated by ai/bench/make_bench_models.py - do not edit\n#pragma once\n#include <stdint.h>\n"]
    hd = ["// Generated by ai/bench/make_bench_models.py - do not edit\n#pragma once\n"
          f"#define BENCH_N_TEST {N_TEST}\n"]
    summary = []
    for name, (m, shape, tflm) in models().items():
        x = rng.normal(size=(N_TEST, *shape)).astype(np.float32)
        y = m.predict(x, verbose=0).ravel().astype(np.float32)
        params = m.count_params()
        hc.append(f"// {name}: {params} parameters, {params * 4} bytes as float32\n")
        hc.append(export_c(name, m))
        hd.append(carr(f"{name}_x", x) + carr(f"{name}_y_ref", y))
        row = [name, params, params * 4, "-"]
        if tflm:
            tfl = to_tflite_int8(m, shape)
            yq, (si, zi, so, zo) = tflite_ref(tfl, x)
            ht.append(f"// {name}: {len(tfl)} bytes int8 flatbuffer\n")
            ht.append(f"alignas(16) static const unsigned char {name}_tflite[{len(tfl)}] = {{"
                      + ", ".join(str(b) for b in tfl) + "};\n")
            ht.append(f"static const float {name}_q[4] = {{{si:.8e}f, {zi}, {so:.8e}f, {zo}}};  // in scale, zp, out scale, zp\n")
            hd.append(carr(f"{name}_y_tfl", yq))
            row[3] = len(tfl)
            print(f"{name}: int8 vs float max error on test inputs = {np.max(np.abs(yq - y)):.4f}")
        summary.append(row)
    for fname, parts in (("models_c.h", hc), ("models_tflm.h", ht), ("bench_data.h", hd)):
        with open(os.path.join(OUT, fname), "w") as f:
            f.write("".join(parts))
    print("\nmodel   params  float32 bytes  int8 tflite bytes")
    for r in summary:
        print(f"{r[0]:<7} {r[1]:>6}  {r[2]:>13}  {r[3]:>17}")


if __name__ == "__main__":
    main()
